name: "build-deploy-dev"

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Name of the preview environment
        required: true
      input:
        type: string
        description: Additional input that can be used in the build process
        required: false
        default: "{}"

permissions:
  contents: read
  id-token: write

env:
  registry: docker.io
  repository: tae2089/omd-demo-server
  BUILD_ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker build push
        uses: tae2089/github-action-modules/actions/docker-build-push@main
        with:
          repository: ${{ env.repository }}
          registry: ${{ env.registry }}
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
          prefix: ${{ env.BUILD_ENV }}
      - name: slack notification
        uses: tae2089/github-action-modules/actions/slack-notify@main
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          action-name: "demo server preview build"
